### ISSUE TITLE
What PCB thickness do i need for the switch?

### ISSUE THREAD

**Issue by chokonmainatsu** [famichu/MagLev_Switch_MX#2]
I'm thinking about making this switch myself, but the only information i'm missing is how thick the pcb has to be, i'll probably order the pcbs at pcbway

**Comment by bobson321** [comment]
1.6mm is in pcb project

**Comment by famichu** [comment]
Thickness of pcbs in switches are 1.0mm. 
I had forgot describe that Information. I'll add that on next commit.
