### ISSUE TITLE
two problems to keypad completion

### ISSUE THREAD

**Issue by bobson321** [famichu/MagLev_Switch_MX#4]
Hi, I am in the process of making your keypad and I have two problems one is 3d printing, we used resin and the printouts are bad(they are falling apart and have wrong dimensions), the second problem is programming atmega bcs I have no clue how to do it. The keypad is almost completed and only these two thing are needed to complete
![image](https://user-images.githubusercontent.com/119765841/216944408-eddf148d-1b2c-4cbb-917e-87e9041ed534.png)

**Comment by famichu** [comment]
Hi, bobson321. Thank you for building my switches and a keyboard.

Firstly, an accuracy of 3D printing are depends on various things. I can't explain all things on here though, you must to do 3 points below at least.

- Find proper settings for that resin on that 3D printer(settings also depends on temperature).
- Append supports as many as you can on edges of the model when you slice(This makes easy to print small parts too).
- Dry printed parts well before secondary hardening(This process makes that parts dimensions more correctly).

And a transparent resin is especially difficult to print as correct dimensions. I recommend to use an opaque resin.
Even with opaque resin, you may need to print 1.5 times as many switches as you need(at least I was)...

Then, to write code to the atmega, you need to use a writer like a USBasp(or you can make this with arduino).
If you use USBasp, [this thread](https://www.instructables.com/Programming-Microcontrollers-With-a-USBasp-Program/) will be helpful.
My code which works on the atmega are made with the Microchip Studio. So you need to Install that first.

**Comment by bobson321** [comment]
Thank you for replying. I have another question what material did you use if resin what type

**Comment by famichu** [comment]
I was using [ELEGOO Water Washable Rapid Resin](https://www.elegoo.com/en-jp/products/elegoo-water-washable-resin).
 But in general, usual resin(non water washable resin) is easier to print detail.

**Comment by bobson321** [comment]
Do you have technical drawing with dimensions? That would be helpful

**Comment by famichu** [comment]
Are you talking about tolerance? I didn't mentioned about that, I was using axises only that has error of size less than 0.5% for width and depth.
If you need to know dimensions(width, depth, height, for each parts'), you can see [my webpage](https://famichu.github.io/htmls/maglev_switch.html#:~:text=%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82-,%E8%A9%B3%E7%B4%B0%E3%82%B9%E3%83%9A%E3%83%83%E3%82%AF,-%E5%B9%85%3A%2013.9mm).
If you need to know more, please open f3z files and measure those in Fusion360.
