### ISSUE TITLE
Would millisecond timer make it work?

### ISSUE THREAD

**Issue by ThunderrGodd** [famichu/MagLev_Switch_MX#5]
Hi, I'm interested in your MagLev switch concept and planning for 60% or 65% keyboard using it.
My plan is RP2040 built-in PCB, but I'm worrying about timer.
Your code is based on microsecond timer, and as I see, default interval is just 1000us(1ms).
As I searched, RP2040 timer is based on milliseconds, so I can't be sure it will work.
How do you think about it? Do you think porting it to RP2040 is possible?
I'm still a beginner at programming, need your advice.

**Comment by famichu** [comment]
Thank you for trying to build my switch.
I think it's possible. But if you build other size of keyborads, I recommend to create programs from scratch. This switch is techniculy just normal linear input devices like a potentiometer. That means it's possible to use with milliseconds timer too(That depends on specification of controllers though).
